spring:
  application:
    name: task-manager
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.springframework: DEBUG
#    org.hibernate: DEBUG
    br.com.rafaelaranda.task_manager: INFO
#    org.springframework.security: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%-35.35thread] [%-36.36logger{36}] : %msg%n"
api:
  security:
    token:
      secret: ${JWT_SECRET:tomatos-with-potatos-with-cheese}